### ISSUE TITLE
Latest flatpak update (1.14.0) doesn't launch maximized anymore

### ISSUE THREAD

**Issue by Froggy232** [flathub/net.sourceforge.liferea#12] opened 2023-01-18 15:41 UTC
Hi,
I have a strange bug : since the latest update (v1.14.0) liferea launch windowed, not maximized.
If I downgrade to previous version, it launch maximized as it should.
Am I the only one with this bug?
Does someone know how to correct this?
I use the flathub version.
Thanks you

**Comment by Froggy232** [comment] 2023-01-18 15:41
I think the issue reside in the file ~/.var/app/net.sourceforge.liferea/config/glib-2.0/settings/keyfile

This file has an entry named "last-window-state" which is on 0. I have tried to put it on 1, but it revert to 0 everytime I open liferea.

**Comment by mikelolasagasti** [comment] 2023-01-21 15:15
I'm not able to reproduce this one. 

- If I close liferea while is maximized, close it and open it, it will be maximized. 
- If I change to windowed view, close it an open it again, it will be windowed. 
- If I maximize it again, close it and re-open it it will be maximized. 

In all those scenarios `last-window-state` is 0 in `~/.var/app/net.sourceforge.liferea/config/glib-2.0/settings/keyfile`. 

I'm using Fedora 37 with GNOME, flatpak version 1.14.1-2.fc37.x86_64 and the test build that was submitted to stable flathub.

**Comment by Froggy232** [comment] 2023-01-21 15:42
Hello,
Thanks for your answer, I don't understand why I have this problem. If I downgrade to previous version, everything work well.
I also understand that it's not related to the keyfile file.
I will continue to investigate.
Thanks!

**Comment by Froggy232** [comment] 2023-01-21 15:58
I just tried with a new profile (by removing ~/.var/app/net.sourceforge.liferea) and the problem is still here.

**Comment by Froggy232** [comment] 2023-01-31 11:43
Hello again,
I just tried with a freshly installed Fedora Silverblue, and I have the exact same problem.
I will continue to search.
Thanks you!

**Comment by bbhtt** [comment] 2023-04-23 01:44
@Froggy232 Are you running in Wayland? This could be related to https://github.com/lwindolf/liferea/issues/901. Seems like others are reporting similar issues https://github.com/lwindolf/liferea/issues/901#issuecomment-1517948717.

**Closed** 2023-04-24 09:55 UTC
